### ISSUE TITLE
Newbie error message when trying to run xcom.getValue for first time

### ISSUE THREAD

**Issue by JeffersM1** [zocker-160/xcom-protocol#2] opened 2023-06-21 12:42 UTC
I am completely new to python and am getting some type of syntaxt error when trying to run in an Ubuntu 22.04 terminal.  This is what I have done so far:
```
michael@michael:~$ pip install xcom-proto
Defaulting to user installation because normal site-packages is not writeable
Collecting xcom-proto
  Downloading xcom_proto-0.2.1-py3-none-any.whl (21 kB)
Collecting pyserial<4.0,>=3.5
  Downloading pyserial-3.5-py2.py3-none-any.whl (90 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 90.6/90.6 KB 604.4 kB/s eta 0:00:00
Installing collected packages: pyserial, xcom-proto
  WARNING: The scripts pyserial-miniterm and pyserial-ports are installed in '/home/michael/.local/bin' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
Successfully installed pyserial-3.5 xcom-proto-0.2.1

michael@michael:~$ cd .local/bin
michael@michael:~/.local/bin$ ls

michael@michael:~/.local/bin$ python3
Python 3.10.6 (main, May 29 2023, 11:10:38) [GCC 11.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.

>>> from xcom_proto import XcomLAN

>>> xcom = XcomLAN("192.168.0.170", dstPort=4001, srcPort=4002)

>>> boostValue = xcom.getValue(param.SMART_BOOST_LIMIT)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name 'param' is not defined
```
Am I missing something in the environment?

**Comment by zocker-160** [comment] 2023-06-21 12:50
First you only ran `from xcom_proto import XcomLAN` which is not enough, as specified in the readme, you also have to import param using `from xcom_proto import XcomP as param`.

Secondly after thinking about the MOXA configuration, I think I have switched the Operation Mode from TCP client to UDP, because I did not want to send my data to the Studer Portal and my current XcomLAN implementation does use UDP. (although I could change it, but I am not sure if then the package logic does still work as I am currently not using it myself, so hard to debug)

And then in UDP mode you have to make sure to set the Data Packing properly (which I think you did have correctly) and set the port to 4001.

**Comment by JeffersM1** [comment] 2023-06-21 13:25
OK, the import param was the problem.  I changed to UPD Operation Mode in the Moxa which killed the communication with the Studer portal.

![image](https://github.com/zocker-160/xcom-protocol/assets/97175692/edbe954c-25c0-414d-b55b-5b4a83bb65a7)

Now I am getting a timeout error:
```
>>> boostValue = xcom.getValue(param.SMART_BOOST_LIMIT)
Waiting for response from XcomLAN timed out
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/michael/.local/lib/python3.10/site-packages/xcom_proto/XcomAbs.py", line 41, in getValue
    response: Package = self.sendPackage(request)
  File "/home/michael/.local/lib/python3.10/site-packages/xcom_proto/XcomLAN.py", line 51, in sendPackage
    value = future.result(10) 
  File "/usr/lib/python3.10/concurrent/futures/_base.py", line 458, in result
    return self.__get_result()
  File "/usr/lib/python3.10/concurrent/futures/_base.py", line 403, in __get_result
    raise self._exception
  File "/usr/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/michael/.local/lib/python3.10/site-packages/xcom_proto/XcomLAN.py", line 68, in _awaitUDPResponse
    response = udpSocket.recv(256)
TimeoutError: timed out
```

**Comment by zocker-160** [comment] 2023-06-21 13:28
Can you try to switch dstPort and srcPort in the XcomLan() constructor?

`xcom = XcomLAN("192.168.0.170", dstPort=4002, srcPort=4001)`

It is possible that I confused the two in the example.

**Comment by JeffersM1** [comment] 2023-06-21 13:43
That was the problem.  Great remote troubleshooting!!!

>>> boostValue = xcom.getValue(param.SMART_BOOST_LIMIT)
>>> print(boostValue)
100.0
>>>

**Comment by zocker-160** [comment] 2023-06-21 13:55
nice!
I need to fix that in the example code, I did indeed confuse the two.

May I ask you for permission to use your screenshot above for the Readme? I think that could help others as well.

As for your other remark, yes UDP mode does disable the Studer Portal, which is how I am running my installation as I don't want to give Studer my data :V.

If you want both, then I would have to take another look at the implementation, because with the current code TCP mode is not going to work.

**Comment by JeffersM1** [comment] 2023-06-21 14:40
Yes you may use the screen shot in the readme.  Let me know if you need any others.  

TCP is something that I will want.  If you are not able to work that one (without a Moxa you will be working blind) maybe someone in one of the forums will be interested in giving it a go.

The battPhase = xcom.getValue(param.BATT_CYCLE_PHASE) gives me an error message.  Maybe it doesn't exist in my system.  Its probably not important to me though.  I have the following hardware:
PV Panels: 18 Recom 460W Shingled Puma monocrystalline
Inverter: 1 Studer XTH 8000-48
Communications: 1 Xcom-LAN (Moxa NPort 5110A & Xcom232), 1 Xcom-CAN, RCC-03
Charge controller: 2 Studer VS-70
Battery: 4 Pylontech US 3000B 3.5KW

I am mainly interested in reading the synoptic data and writing to RAM parameter 6062: SOC level for backup and maybe 6063: SOC level for grid feeding.  Would be nice to be able to read those parameters from RAM, but if its not possible, I should be able to deduce from the system behavior.

I will have to test out writing to RAM parameter 6062 tomorrow morning once the battery has partially discharged.  Right now it is full.

**Comment by zocker-160** [comment] 2023-06-21 15:16
> TCP is something that I will want. If you are not able to work that one (without a Moxa you will be working blind) maybe someone in one of the forums will be interested in giving it a go.

I do have a Moxa, but I am not using it, so the main issue is simply having the time to set everything up again and making it work.

But I do remember trying to make it work once with TCP, but I sadly don't remember exactly why I abandoned that approach (it was a few years back, probably 2019 or so).

> The battPhase = xcom.getValue(param.BATT_CYCLE_PHASE) gives me an error message

What is the error you are getting? It should print it out.

As for 6062 and 6063 I cannot say if those will work, as I personally don't use them and they are not defined under param currently, so you will have to use the `getValueByID` function and pass the parameter type as well.

If it gives you a permission error, then there is the possibility that the 6xxx params are under TYPE_INFO instead of TYPE_PARAM. I have fought this issue quite often as the Studer documentation does not say what the type is.

**Comment by JeffersM1** [comment] 2023-06-21 15:38
This is the battPhase error: 
```
>>> battPhase = xcom.getValue(param.BATT_CYCLE_PHASE)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/michael/.local/lib/python3.10/site-packages/xcom_proto/XcomAbs.py", line 41, in getValue
    response: Package = self.sendPackage(request)
  File "/home/michael/.local/lib/python3.10/site-packages/xcom_proto/XcomLAN.py", line 62, in sendPackage
    raise KeyError("Error received", errCode)
KeyError: ('Error received', 'OBJECT_ID_NOT_FOUND')
```

Does your protocol support requesting synoptic data?  
In a JSON request to the portal is like:
```
value_template: '42'
    json_attributes:
      - energy
      - battery
      - power
```


The response come back like:
```
{
  "energy": {
    "hasSolar": true,
    "solar": 20.26,
    "yesterdaySolar": 28.88,
    "solarUnit": "kWh",
    "hasInverter": true,
    "gridGenset": 5.91,
    "yesterdayGridGenset": 6.09,
    "gridGensetUnit": "kWh",
    "load": 20,
    "yesterdayLoad": 31,
    "loadUnit": "kWh",
    "hasBatteryStatusProcessor": true,
    "batteryCharge": 106.06,
    "batteryChargeUnit": "Ah",
    "yesterdayBatteryCharge": 90.12,
    "batteryDischarge": 35.66,
    "batteryDischargeUnit": "Ah",
    "yesterdayBatteryDischarge": 91.56
  },
  "battery": {
    "power": 0.11,
    "powerUnit": "kW",
    "voltage": 51.28,
    "voltageUnit": "V",
    "current": 1.9,
    "currentUnit": "A",
    "soc": 97,
    "socUnit": "%",
    "temperature": 27.59,
    "temperatureUnit": "°C",
    "temperatureUnitHtml": "&#176;C",
    "hasBatteryStatusProcessor": true
  },
  "power": {
    "hasSolar": true,
    "solar": 3.17,
    "solarUnit": "kW",
    "hasInverter": true,
    "gridGenset": 0.23,
    "gridGensetUnit": "kW",
    "load": 3.01,
    "loadUnit": "kW",
    "hasBatteryStatusProcessor": true,
    "battery": 0.11,
    "batteryUnit": "kW"
  }
}
```

**Comment by zocker-160** [comment] 2023-06-21 21:23
> This is the battPhase error:

Ok makes sense, that value does not seem to exist in your setup.

> Does your protocol support requesting synoptic data?

I doesn't, I wanted to keep it as simple as possible and adding such feature would be quite a lot of effort actually.

**Comment by JeffersM1** [comment] 2023-06-22 03:40
I am getting a syntax error when trying to follow the print .join examples in the readme:
```
>>> boostValue = xcom.getValue(param.SMART_BOOST_LIMIT)
>>> soc = xcom.getValue(param.BATT_SOC)
>>> battCurr = xcom.getValue(param.BATT_CURRENT)
>>> battVolt = xcom.getValue(param.BATT_VOLTAGE)
>>> 
>>> print(boostValue)
100.0
>>> print(soc)
68.0
>>> print(battCurr)
0.0
>>> print(battVolt)
49.875
```
but if I try to use the print .join in the example I get:
```
>>> print("|".join([boostValue, soc, battCurr, battVolt]))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: sequence item 0: expected str instance, float found
>>> 
```

What is the syntax for using getValueByID?  I have tried:
```

>>> socbacklevel = xcom.getValueByID(6062, TYPE_FLOAT, "%") 
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name 'TYPE_FLOAT' is not defined
>>> socbacklevel = xcom.getValueByID(6062, TYPE_PARAM, "%") 
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name 'TYPE_PARAM' is not defined
>>> socbacklevel = xcom.getValueByID(6062, TYPE_INFO, "%") 
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name 'TYPE_INFO' is not defined
```
When I try to read the view only user level (parameter 5012) I get the following even though I see it defined in your parameter list.
```
>>> userlevel = xcom.getValue(param.USER_LEVEL) 
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/michael/.local/lib/python3.10/site-packages/xcom_proto/XcomAbs.py", line 41, in getValue
    response: Package = self.sendPackage(request)
  File "/home/michael/.local/lib/python3.10/site-packages/xcom_proto/XcomLAN.py", line 62, in sendPackage
    raise KeyError("Error received", errCode)
KeyError: ('Error received', 'ACCESS_DENIED')
```
In the remote console served by the Studer portal, I can see that the current user level is Installer, parameter 5012 = 48 decimal (30 hex)

That there isn't a get synoptic probably won't be a problem for me.  Visually the CLI response time looks to be reasonably fast.  Currently in Home Assistant I am running JSON synoptic requests to the Studer portal every 10 seconds, which I could push down to 5 seconds, but probably not much less than that.  I am expecting that the python protocol will be an improvement.  Also the portal hasn't been as reliable as I would like with its ignored requests and responses of all 0's.  This morning (22 June 2023) it is down for maintenance from  5:00 a.m. CEST to 9:00 a.m. CEST.

**Comment by zocker-160** [comment] 2023-06-22 10:11
> but if I try to use the print .join in the example I get:

yeah I messed up the example, I am sorry about that, shouldn't have done it late at night :D
the correct version is to simply pass all variables to print:

```python
print(boostValue, soc, battCurr, battVolt)
```
> What is the syntax for using getValueByID? I have tried:

You have to import the constant types with 
`from xcom_proto import XcomC`
and then call it with
```py
socbacklevel = xcom.getValueByID(6062, XcomC.TYPE_FLOAT)
```

> When I try to read the view only user level (parameter 5012) I get the following even though I see it defined in your parameter list.

Yeah it does not work for me either, I have it defined, because it is something I wanted to fix at some point, but I never got around to it, because I personally currently don't need it.

The reason why it doesn't work, is because there are some special parameters (and user level is one of them) which need special treatment in the request.

It needs a special package to be sent using `XcomC.QSP_LEVEL`, but again as I said, I have not implemented it in the protocol.

> In the remote console served by the Studer portal, I can see that the current user level is Installer, parameter 5012 = 48 decimal (30 hex)

Yeah this is an issue, I actually have not managed to figure out yet. 

It seems like the Studer Portal has special treatment, because the Xcom-RS232 which is connected to the Moxa has its own user level independent of the Portal (which can be queried directly when connecting using a direct USB adapter) and it is always the lowest unless you manually overwrite it.

So there is something going on, I sadly don't understand myself, but the main issue is that every RCC has its own user level.

As for the speed, the current UDP implementation is not optimized for speed, but it should be faster than going though Studer's webserver.
One big improvement I could see myself implementing is being able to do a bulk request of many values at once, but I probably won't have the time to do that anytime soon sadly.

**Comment by JeffersM1** [comment] 2023-06-23 10:44
These are all of the sensors that I am currently pulling from the Studor portal using JSON requests:
![image](https://github.com/zocker-160/xcom-protocol/assets/97175692/11df00bd-37fe-4887-bbbc-582036482be8)

Using the Xcom-protocol I am able to read all of them locally through the Xcom-LAN (the readings were taken a couple of minutes before the Home Assistant screen capture above so that could account for some of the variation):
```
>>> 
>>> batt_charge = xcom.getValueByID(7007, XcomC.TYPE_FLOAT)
>>> print('batt_charge = ',batt_charge, 'Ah')
batt_charge =  86.8125 Ah
>>> 
>>> batt_discharge = xcom.getValueByID(7008, XcomC.TYPE_FLOAT)
>>> print('batt_discharge = ',batt_discharge, 'Ah')
batt_discharge =  23.890625 Ah
>>> 
>>> battpower = xcom.getValueByID(7003, XcomC.TYPE_FLOAT)
>>> print('battpower = ',battpower/1000, 'kW')
battpower =  0.080875 kW
>>> 
>>> soc = xcom.getValue(param.BATT_SOC)
>>> print('soc = ',soc, '%')
soc =  97.0 %
>>> 
>>> batttemp = xcom.getValue(param.BATT_TEMP) 
>>> print('batttemp = ',batttemp, '°C')
batttemp =  27.40625 °C
>>> 
>>> battery_voltage = xcom.getValue(param.BATT_VOLTAGE) 
>>> print('battery_voltage = ',battery_voltage, 'V')
battery_voltage =  50.5625 V
>>> 
>>> grid_prod = xcom.getValue(param.AC_ENERGY_IN_CURR_DAY)
>>> print('grid_prod = ',grid_prod, 'kWh')
grid_prod =  3.734375 kWh
>>> 
>>> gridpower = xcom.getValue(param.AC_POWER_IN) 
>>> print('gridpower = ',gridpower, 'kw')
gridpower =  0.10498046875 kw
>>> 
>>> houseload = xcom.getValue(param.AC_POWER_OUT) 
>>> print('houseload = ',houseload, 'kW')
houseload =  1.095703125 kW
>>> 
>>> solarpower = xcom.getValueByID(15010, XcomC.TYPE_FLOAT)
>>> print('solarpower = ',solarpower, 'kW')
solarpower =  0.6337890625 kW
>>> 
>>> solarpower1 = xcom.getValueByID(15011, XcomC.TYPE_FLOAT)
>>> print('solarpower1 = ',solarpower, 'kW')
solarpower1 =  0.6337890625 kW
>>> 
>>> solarpower2 = xcom.getValueByID(15012, XcomC.TYPE_FLOAT)
>>> print('solarpower2 = ',solarpower, 'kW')
solarpower2 =  0.6337890625 kW
>>> 
>>> solar_prod = xcom.getValueByID(15017, XcomC.TYPE_FLOAT)
>>> print('solar_prod = ',solar_prod,'kwh')
solar_prod =  4.84765625 kwh
>>> 
>>> solar_prod1 = xcom.getValueByID(15018, XcomC.TYPE_FLOAT)
>>> print('solar_prod1 = ',solar_prod,'kwh')
solar_prod1 =  4.84765625 kwh
>>> 
>>> solar_prod2 = xcom.getValueByID(15019, XcomC.TYPE_FLOAT)
>>> print('solar_prod2 = ',solar_prod,'kwh')
solar_prod2 =  4.84765625 kwh
>>> 

```
I'm not quite sure why the solar power parameters 15010, 15011, and 15012 are all exactly the same values.  Same for solar production parameters 15017, 15018, and 15019.  I have two VarioStrings with each fed by the same number and size of panels, but I wouldn't expect them to be so perfectly matched.  This will be a good question for Studer.  

I would like to explore writing to parameter 6062 which is the SOC Level for Backup.  I'm not able to change that through the JSON API either, but Studer is looking into it for me.  When I try to write to this parameter using the Xcom-protocol, I get an "Access Denied" message.  You had said this could be caused by the permission level on the Xcom-232i being set to low.  Is there a way to set the Xcom-232i user level from the RCC or using some other method that you know of?  If so, what would be the parameter number?  Also, do you know if it use the same levels: Info 0 (0 hex), Basic 16 (10 hex), Expert 32 (20 hex), Expert 48 (30 hex), and Qualified Service Partner (QSP) 64 (40 hex)?

**Comment by zocker-160** [comment] 2023-06-24 15:55
>  I have two VarioStrings

It is possible that only one is answering (just a guess as I cannot test it myself). the `getValue` function does have an optional parameter called `dstAddr` which is set to 100 (broadcast) by default. You might try to set it to the address of one of your VarioStrings and see if that will give you a different return value.

>  You had said this could be caused by the permission level on the Xcom-232i being set to low.

Do you know by any chance if 6062 is TYPE_INFO or TYPE_PARAMETER? Currently my implementation is treating it as PARAMETER, which could also be the cause of the issue (also just a guess, since I don't use that parameter myself, I actually don't have it at all IIRC).

I have implemented the `XcomC.QSP_LEVEL_INSTALLER` and `XcomC.QSP_LEVEL_EXPERT` levels of permission setting, sadly I never could get it to work (I also always get Permission Denied).

I am probably doing something wrong in the implementation, but I personally don't need it for setting my BOOST parameter, which is why I never actually bothered to look into that issue.

**Comment by JeffersM1** [comment] 2023-06-25 05:13
> I am probably doing something wrong in the implementation, but I personally don't need it for setting my BOOST parameter, which is why I never actually bothered to look into that issue.

Do you have a strategy to use the BOOST parameter to reduce energy cost by taking advantage of off peak or night rates?  I wanted to use the SOC Backup Level to force charging of the battery at night if the rates are very low or negative.

**Comment by zocker-160** [comment] 2023-06-25 10:34
I have solar power together with a battery and coupled with weather forecast to calculate an estimate of energy production for the next day.

Depending on the forecast I then use the BOOST value to regulate a minimum SOC level in order to minimize battery wear and maximize solar power.

I don't use grid power to charge the battery at all since I pay the same rate 24h and my battery is a pure solar buffer.

PS: I am a bit confused as to why you are using parameter 6062 as that is - according to the Studer protocol doc - a value assigned to Xcom-CAN? Is your battery connected to Xcom-CAN?

**Comment by JeffersM1** [comment] 2023-06-25 11:31
> I have solar power together with a battery and coupled with weather forecast to calculate an estimate of energy production for the next day.

I am using the integration Forecast.Solar which gives an estimate of the current and next day solar energy for my system taking into consideration panels, orientation, weather and some other lesser factors.  I use it to decide what to run.

> Depending on the forecast I then use the BOOST value to regulate a minimum SOC level in order to minimize battery wear and maximize solar power.

I would like to know more about this approach.   I thought the BOOST was to add inverter power to the existing grid power.  Are you using the BOOST, maybe with another parameter to somehow back off on inverter power when there is less solar?  
 
> I don't use grid power to charge the battery at all since I pay the same rate 24h and my battery is a pure solar buffer.

I just switched electric supplier from one that gave me three different tariff brackets through out the day.  I would just charge the battery on solar with that arrangement.  Now I just switched to a new supplier (Still waiting for my first bill. ) that charges spot rates that change every hour.   Sometimes the rates go negative in the mid afternoon or early morning hours.  Normally during the the system charges up to 97%, then at night it will discharge down to a reserve level of 68%.  The 68% is to save wear and tear on the LiFePO4 battery and to act as a reserve in case the grid were to go south.  With the new tariff there is the opportunity to charge up the battery a second time, get paid for it, and start off the day with a near full battery which is especially helpful if expecting a cloudy morning or day to get through the late morning / early afternoon peak rate period.  Already I am able to automatically turn on some loads like water heater, distiller, and dehumidifier when rates go low or negative.

The screen shot below shows an example of the tariff and where I manually increased the 6062 parameter to 96% at 3 AM to charge the battery.  I stopped charging at about 4:30 AM when it got to 90% and I got tired again and went back to sleep.  The battery slowly discharged to about 82% to run the house while waiting for a charge from solar.  I want to make sure the battery is charged before going into the time period when the rates are highest.  The dropouts in the SOC are from when the Studer portal stops cooperating.  These portal problems happen whether using HA JSON requests, Studer Easy Monitor Android app, or a web browser connected to the Studer portal.  All three see a problem at the same instants.
![image](https://github.com/zocker-160/xcom-protocol/assets/97175692/d1adf3c5-2ce3-4c72-9b4a-fc7029b90eb1)


> PS: I am a bit confused as to why you are using parameter 6062 as that is - according to the Studer protocol doc - a value assigned to Xcom-CAN? Is your battery connected to Xcom-CAN?  

Yes, my battery is a Pylon Tech.  Seems that many 3rd party battery systems use CAN bus for communication.  I believe the Pylon Tech uses its own BMS and the Studer just monitors it and sets the parameters.  This seems to be a standard configuration used by the local Solar Shop supplier.  When there is no solar, the battery is allowed to discharge down to the value set by 6062, and after that it switches over to grid power and the house runs on grid.  If I increase the 6062 parameter while there is no solar, grid power is used to charge the battery up to the new setting.

**Comment by zocker-160** [comment] 2023-06-25 15:00
Ah ok understood, I understand now what you are trying to do. My setup is very different as I only control the discharge level of the battery but never actually charge from the grid (would be stupid as I have the same very high price all the time).

> I would like to know more about this approach. I thought the BOOST was to add inverter power to the existing grid power. Are you using the BOOST, maybe with another parameter to somehow back off on inverter power when there is less solar?

Sure so it is actually pretty simple: BOOST controls how many % of the max sustained power of your inverter can be pulled at most out of the battery.

So lets say the house pulls 1000W and you got the 2400W inverter, then setting 50% BOOST will pull all 1000W out of the battery. 
If you set BOOST to 10% it will only pull 100W from the battery and the remaining 900W from the grid and setting 0% will be no power from battery all everything from the grid.

I use that to control the minimum SOC level of the battery by pulling out of the battery as long as there is solar or as long as a minimum SOC is not reached. The moment it is reached, I set boost to 0%. (In summer this basically never happens)

I also use it during the charge phase in order to boost exactly the amount of power needed to make the battery not discharge (ideally 0W, but usually I end up with around 50W, calculation is not 100% accurate).

By doing this I could reduce battery cycles to almost 1/10th of what it originally did with the default settings and drop the amount of bought electricity from the grid by up to 5x (from 12 kWh to 2kWh in summer (on average, on a sunny day it would be almost 0) and around 5kWh in winter).

Here a small graph for a sunny day in summer:

![Screenshot_20230625_165305](https://github.com/zocker-160/xcom-protocol/assets/36563538/cdf5b74f-7d9f-4fb6-91ee-dca7065c9d70)

In charge phase BOOST follows PV power to prevent discharge and during hold it tries to keep 100% as long as possible using all solar that is available and then switch to dischage the moment solar drops below 100W.

With that approach I only have around a 20 - 25% charge cycle every day with micro cycles completely eliminated.

EDIT: [link to Czech forum as my own reminder](https://solarforum.cz/viewtopic.php?t=496&sid=87503894086308a38c7f7e6b2161bf71&start=375)

**Comment by JeffersM1** [comment] 2023-11-22 18:02
Hi Zocker-160.

I have someone working on a TCP server for me to use with your Xcom-protocol instead of the UDP.  Once he is done, I will test it from my laptop.  Eventually I would like to install it on the Pi that is running my Home Assistant installation.  It is a Raspberry Pi 4B, 8 GB running Debian, Docker running in Debian, and HA Container running in a Docker container.

Can you give any recommendations on integration into HA?  What are the integration options?   What do you use in your setup?  What would you recommend for me to integrate the Xcom-protocol into HA?

**Comment by zocker-160** [comment] 2023-11-22 18:29
Hi @JeffersM1,

> I have someone working on a TCP server for me to use with your Xcom-protocol instead of the UDP. Once he is done, I will test it from my laptop. 

Would highly appreciate if he could create a Pull Request for this repo, so others can benefit from it as well.

> Can you give any recommendations on integration into HA? What are the integration options? What do you use in your setup? What would you recommend for me to integrate the Xcom-protocol into HA?

This depends on if you want to only read the values in HA or also write them from the HA UI.

Generally you have 3 options:

- Create a HA plugin for xcom-protocol (not easy and would not recommend, although others could then just install it with a single click)
- Use MQTT (more advanced setup, but with that you could also read the values from other clients outside of HA and you could also implement the writing of values, would need implementing an MQTT client for xcom and a broker of course, but that is simply to install
- Use [HA's REST HTTP API](https://developers.home-assistant.io/docs/api/rest/) (which is what I use, is the easiest to implement but is read only)

I am willing to share some of my HA integration code if you are interested.

**Comment by JeffersM1** [comment] 2023-11-22 19:01
Hi @zocker-160 

Thanks for the reply.  Adding the pull request isn't in the scope of his work, but I should be able to do that, although I have never done one.  I will have the code once he finishes.

I would like to be able to write values so I would probably go the MQTT route, but would probably start off using the RESTful approach to read values.  Currently I am using RESTful integration to read Synoptic data from the Studer cloud every 15 seconds.  I want to use the Xcom protocol to do several reads a minutes, and a few writes per day.  I thought that you were performing writes so that you could control the Boost parameter, or are you doing that outside of HA?

I am interested in seeing your HA integration code.  I'm sure hat it would help me to get this up and running sooner.

**Comment by JeffersM1** [comment] 2023-11-22 21:07
@zocker-160 it looks like I had confused the RESTful API that you had used with the RESTful integration https://www.home-assistant.io/integrations/rest/ that I have been using to read data from the Studer cloud.  

I see that both RESTful API and integration have POST actions.  Had you tried using the POST action to write parameter values to your system?

**Comment by zocker-160** [comment] 2023-11-22 22:02
@JeffersM1 

>  I thought that you were performing writes so that you could control the Boost parameter, or are you doing that outside of HA?

I am doing the writes / controlling outside of HA, I use HA only for monitoring.

> I see that both RESTful API and integration have POST actions. Had you tried using the POST action to write parameter values to your system?

As I have linked above (this one: https://developers.home-assistant.io/docs/api/rest/) HA offers a simple REST API where you can use HTTP POST to send new sensor data and states. It is very simple to implement and the values are visible immediately in the UI.

But as I said, it is read only as the API is only one way.
Implementing a two way REST API makes no sense as at that point using MQTT would be smarter IMO.

**Comment by JeffersM1** [comment] 2023-11-28 10:04
Hi  @zocker-160  the developer that I have working on the TCP Server for Xcom-protocol would like to make a pull request, but requires to be part of the repository either through a token or email.

**Comment by zocker-160** [comment] 2023-11-28 16:16
@JeffersM1 awesome, thank you!

I have sent him a colab request, when he accepts it, he will be able to push to this repository.

**Comment by JeffersM1** [comment] 2023-11-28 16:19
Thanks.  I will delete his email address from this post so he doesn't get spammed.

**Comment by JeffersM1** [comment] 2023-11-30 09:07
Hi @zocker-160.  The pull request has been made and the new code uploaded.  The developer has the following questions:

1. Has the pull request been merged?
2. why is he installing this as a library? is it being pulled from the main branch of the repository? if I push something on the github he sent it does not automatically get into the main branch they have to be merged by the controller of the project who also has to review
3. Does he have experience collaborating on GitHub?


I was able to download the devoloper's code from https://github.com/zocker-160/xcom-protocol/tree/test_xcom_lan_tcp , but when I try to run it I get the errors listed in the file attached to the conversations of that branch https://github.com/zocker-160/xcom-protocol/pull/3 .  Any idea of what is causing the errors?

**Comment by zocker-160** [comment] 2023-11-30 18:32
Hi @JeffersM1 

> Has the pull request been merged?

No because you were reporting an issue and I was expecting the dev to react, but I am in general willing to merge, although it will need a bit of cleanup

> is it being pulled from the main branch of the repository?

yes, the main branch is protected for a reason, I only want code there that I will also push to PyPi repo

> if I push something on the github he sent it does not automatically get into the main branch they have to be merged by the controller of the project who also has to review

yes that is me, this is on purpose, I want to see what is being merged (makes sense I think)

>  Any idea of what is causing the errors?

I have not looked into it yet (will do that today), but I would guess that the import paths of the submitted code are not correct.

**Comment by JeffersM1** [comment] 2023-12-01 10:15
Hi @zocker-160  .  The developer has updated the code (3 commits ahead).  Now I am no longer getting the error messages when initializing.  But am not getting data from Xcom-LAN.

```
# Start python3 environment
python3

# these four statements are used to initialize the communications and only need to be done once:

from xcom_proto import XcomP as param
from xcom_proto import XcomC
from xcom_proto import XcomLAN
xcom = XcomLAN("192.168.0.170", dstPort=4001, srcPort=4002)
# no error responses this time

# Run test commands to read data from local Xcom-LAN
batt_charge = xcom.getValueByID(7007, XcomC.TYPE_FLOAT)
print('batt_charge = ',batt_charge, 'Ah')

# Got following response:
 
>>> batt_charge = xcom.getValueByID(7007, XcomC.TYPE_FLOAT)
print('batt_charge = ',batt_charge, 'Ah')  # missing python3 prompt and no response with values

# correct response, as observed when using published UDP version of XcomLAN.py:
>>> batt_charge = xcom.getValueByID(7007, XcomC.TYPE_FLOAT)
>>> print('batt_charge = ',batt_charge, 'Ah')
batt_charge =  86.8125 Ah
```
Any thoughts?

**Comment by JeffersM1** [comment] 2023-12-01 10:24
@zocker-160 do you do freelance work on fiverr or any other platform?  I am wondering if I need to reassess my options for getting this code to work.

**Comment by JeffersM1** [comment] 2023-12-01 10:36
@zocker-160  That after running a read command
>>> batt_charge = xcom.getValueByID(7007, XcomC.TYPE_FLOAT)
that I don't get the python command prompt back, makes me think there is still something missing in the connection between the new code and the existing code.

**Comment by JeffersM1** [comment] 2023-12-01 11:12
@zocker-160  Running a read command in a Visual Studio terminal, I get the following:

>>> batt_charge = xcom.getValueByID(7007, XcomC.TYPE_FLOAT)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name 'xcom' is not defined. Did you mean: 'XcomC'?

**Comment by JeffersM1** [comment] 2023-12-01 12:18
Hi @zocker-160 are you available for a virtual meeting with the developer Saturday 02 December 19:00 (UTC+0) or
Saturday 11:40 (UTC+0)?

**Comment by JeffersM1** [comment] 2023-12-01 12:48
@zocker-160 I just uninstalled the code, reinstalled it, and ran in Studio Code terminal, and this is the error response:

![Screenshot from 2023-12-01 12-44-44](https://github.com/zocker-160/xcom-protocol/assets/97175692/969cc95b-4e53-42d7-bfa3-cf6460b68ee1)

**Comment by zocker-160** [comment] 2023-12-01 13:08
@JeffersM1 

I added a review with a few comments.

Does the dev even have access to a Moxa? 
Because to me his code is not going to work. I could be wrong, but in order to make TCP work, one needs to implement an TCP listener which is listening all the time and not only when you are expecting data (like I do with the UDP implementation)

UDP is stateless and connectionless, which is why that works, it does not matter when you listen as long as you listen when data is transferred
You cannot do the same with TCP unless the server is doing a connection + handshake every time for each package, which I currently doubt the Moxa does.

> do you do freelance work on fiverr or any other platform? I am wondering if I need to reassess my options for getting this code to work.

Yes I do, but I am currently very busy sadly. If the TCP mode of the Moxa works the way I think it does (I could be wrong, this is just a guess) then implementing that is more involved than just changing a few variables.

**Comment by zocker-160** [comment] 2023-12-01 13:09
> I just uninstalled the code, reinstalled it, and ran in Studio Code terminal, and this is the error response

This seems to be an unrelated issue to me. Here there is simply no data coming back inside the defined time frame (2 seconds by default)

**Comment by zocker-160** [comment] 2023-12-01 13:11
> that I don't get the python command prompt back, makes me think there is still something missing in the connection between the new code and the existing code.

Yeah to me this makes sense, because I think the code does not work. IIRC the Moxa does only this weird listener port dance when in UDP mode, otherwise the connection to the Studer Cloud would not work either as it cannot send data to your local address.

**Comment by JeffersM1** [comment] 2023-12-02 10:00
> > do you do freelance work on fiverr or any other platform? I am wondering if I need to reassess my options for getting this code to work.
> 
> Yes I do, but I am currently very busy sadly. If the TCP mode of the Moxa works the way I think it does (I could be wrong, this is just a guess) then implementing that is more involved than just changing a few variables.

Although you are currently very busy, do you foresee having time available in the future to add TCP Server to your code?  If not, is there anyone else that you could recommend?

**Comment by zocker-160** [comment] 2023-12-02 12:33
> Although you are currently very busy, do you foresee having time available in the future to add TCP Server to your code? If not, is there anyone else that you could recommend?

@JeffersM1 how can I contact you? Some kind of Instant Messenging would be nice (Discord?) I currently don't have a Moxa set up, but you could help me by connecting it to one of my servers, I then could try to implement it that way.

**Comment by JeffersM1** [comment] 2023-12-02 13:16
My user name on Discord is <>  I also have Telegram, WhatsApp and Google Chat.

**Comment by zocker-160** [comment] 2023-12-02 14:03
sent you a friend request

**Comment by zocker-160** [comment] 2023-12-02 14:32
@JeffersM1 sent you a friend request, if you react within a few hours, I might be able to look into it today.

**Comment by zocker-160** [comment] 2023-12-14 00:27
closing as your original issue is resolved

**Closed as completed by zocker-160** 2023-12-14 00:27 UTC
